#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────
# IP-Cam-Master Installer / Updater
# Usage: curl -fsSL https://raw.githubusercontent.com/meintechblog/ip-cam-master/main/install.sh | bash
# ──────────────────────────────────────────────────────

APP_DIR="/opt/ip-cam-master"
SERVICE_NAME="ip-cam-master"
REPO_URL="https://github.com/meintechblog/ip-cam-master.git"

# ── Helpers ───────────────────────────────────────────

banner() {
  echo ""
  echo "======================================"
  echo "  IP-Cam-Master Installer"
  echo "======================================"
  echo ""
}

step() {
  echo ">> $1"
}

error_exit() {
  echo ""
  echo "FEHLER: $1" >&2
  exit 1
}

trap 'error_exit "Installation abgebrochen. Pruefe die Ausgabe oben."' ERR

# ── Pre-checks ────────────────────────────────────────

banner

if [ "$(id -u)" -ne 0 ]; then
  error_exit "Dieses Skript muss als root ausgefuehrt werden. Verwende: sudo bash install.sh"
fi

# ── Detect mode ───────────────────────────────────────

if [ -d "$APP_DIR" ]; then
  MODE="update"
  step "Vorhandene Installation erkannt. Update-Modus."
else
  MODE="install"
  step "Keine Installation gefunden. Neuinstallation."
fi

# ══════════════════════════════════════════════════════
# FRESH INSTALL
# ══════════════════════════════════════════════════════

if [ "$MODE" = "install" ]; then

  # 1. System dependencies
  step "Installiere Systemabhaengigkeiten (curl, git, ffmpeg)..."
  apt-get update -qq
  apt-get install -y -qq curl git ffmpeg > /dev/null

  # 2. Node.js 22 LTS via NodeSource
  if ! command -v node &> /dev/null || [ "$(node -v | cut -d. -f1 | tr -d v)" -lt 22 ]; then
    step "Installiere Node.js 22 LTS..."
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - > /dev/null 2>&1
    apt-get install -y -qq nodejs > /dev/null
  else
    step "Node.js $(node -v) ist bereits installiert."
  fi

  # 3. Clone repo
  step "Klone Repository nach $APP_DIR..."
  git clone "$REPO_URL" "$APP_DIR"

  cd "$APP_DIR"

  # 4. Install dependencies (production only)
  step "Installiere npm-Abhaengigkeiten..."
  npm install --omit=dev

  # 5. Create data directory
  mkdir -p data

  # 6. Generate .env if missing
  if [ ! -f .env ]; then
    step "Erstelle .env mit zufaelligem DB_ENCRYPTION_KEY..."
    DB_ENCRYPTION_KEY=$(openssl rand -hex 32)
    cat > .env <<EOF
# Auto-generated by IP-Cam-Master installer
DB_ENCRYPTION_KEY=$DB_ENCRYPTION_KEY
EOF
  else
    step ".env existiert bereits, ueberspringe."
  fi

  # 7. Build
  step "Baue Anwendung..."
  npm run build

  # 8. DB migration
  step "Fuehre Datenbank-Migration aus..."
  npx drizzle-kit push

  # 9. systemd service
  step "Richte systemd-Service ein..."
  cp ip-cam-master.service /etc/systemd/system/
  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME"
  systemctl start "$SERVICE_NAME"

  # 10. SSH key setup (optional)
  echo ""
  echo "──────────────────────────────────────"
  echo "  SSH-Key fuer Proxmox einrichten"
  echo "──────────────────────────────────────"
  echo ""
  read -rp "Proxmox Host IP eingeben (oder Enter zum Ueberspringen): " PROXMOX_IP

  if [ -n "$PROXMOX_IP" ]; then
    SSH_KEY="/root/.ssh/ip-cam-master"
    if [ ! -f "$SSH_KEY" ]; then
      step "Generiere SSH-Key..."
      mkdir -p /root/.ssh
      ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -q
    else
      step "SSH-Key existiert bereits: $SSH_KEY"
    fi
    step "Kopiere SSH-Key auf Proxmox-Host ($PROXMOX_IP)..."
    ssh-copy-id -i "${SSH_KEY}.pub" "root@${PROXMOX_IP}"
    echo ""
    echo "SSH-Key wurde eingerichtet. Kein Passwort mehr noetig."
  fi

  # Done
  APP_IP=$(hostname -I | awk '{print $1}')
  echo ""
  echo "======================================"
  echo "  Installation erfolgreich!"
  echo "  IP-Cam-Master laeuft auf http://${APP_IP}"
  echo "======================================"
  echo ""

# ══════════════════════════════════════════════════════
# UPDATE
# ══════════════════════════════════════════════════════

elif [ "$MODE" = "update" ]; then

  cd "$APP_DIR"

  # 1. Stop service
  step "Stoppe $SERVICE_NAME..."
  systemctl stop "$SERVICE_NAME" || true

  # 2. Pull latest
  step "Lade neueste Version..."
  git pull

  # 3. Install dependencies
  step "Aktualisiere npm-Abhaengigkeiten..."
  npm install --omit=dev

  # 4. Build
  step "Baue Anwendung..."
  npm run build

  # 5. DB migration
  step "Fuehre Datenbank-Migration aus..."
  npx drizzle-kit push

  # 6. Update service file
  step "Aktualisiere systemd-Service..."
  cp ip-cam-master.service /etc/systemd/system/
  systemctl daemon-reload

  # 7. Start service
  step "Starte $SERVICE_NAME..."
  systemctl start "$SERVICE_NAME"

  echo ""
  echo "======================================"
  echo "  Update erfolgreich."
  echo "  IP-Cam-Master wurde neu gestartet."
  echo "======================================"
  echo ""

fi
